## This github action runs Checkov against any terraform in the base directory. 
## Checkov generates findings and shows them in the actions tab.

name: Checkov
on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - '**/*.tf'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform 
          quiet: true
          #skip_check: CKV_AWS_01